CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    age INTEGER,
    point INTEGER DEFAULT 0,
    gender TEXT
);

SELECT * FROM users;

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_name INTEGER NOT NULL,
    message TEXT NOT NULL,
    FOREIGN KEY (id_name) REFERENCES users(id) 
);

SELECT * FROM messages;

